---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Instance
Parameters:
  Environment:
    Type: String
    Description: Used for miscellaneous object names and tags
    AllowedValues:
      - "dev"
      - "test"
      - "qa"
      - "prod"
    Default: dev
  HostName:
    Description: The route53 HostedZoneName
    Type: String
  RDSEndpoint:
    Description: The rds endpoint
    Type: String
  ASSETS3Bucket:
    Description: The s3 Bucket Name
    Type: String
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair
  EC2SubnetId:
    Description: Name of an existing Subnet ID
    Type: String
  EC2SecurityGroups:
    Type: CommaDelimitedList
    Description: public access
  EC2ImageId:
    Type: String
    Description: ImageId for ec2-instance
    Default: ami-0a1556aa32684eded
  
Resources:
  EC2Instance:
    DependsOn:
      - EIPAddress

    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref EC2ImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds: !Ref EC2SecurityGroups
      KeyName: !Ref KeyName
      SubnetId: !Ref EC2SubnetId
      Tags:
        - Key: Name
          Value: !Join ["", ["ubuntu_instance_", !Ref Environment]]
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash
              CONF="/etc/environment"
              echo "RDS_ENDPOINT=${RdsEndpoint}" >> $CONF
              echo "ASSET_S3_BUCKET=${AssetS3Bucket}" >> $CONF
              echo "HOST_NAME=${HostZoneName}" >> $CONF                    
            - RdsEndpoint: !Ref RDSEndpoint
              AssetS3Bucket: !Ref ASSETS3Bucket
              HostZoneName: !Ref HostName  

  EIPAddress:
    Type: AWS::EC2::EIP
  EIPAssoc:
    DependsOn:
      - EC2Instance
      - EIPAddress
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance
      EIP: !Ref EIPAddress
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: EC2Instance
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      Fn::GetAtt:
        - EC2Instance
        - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      Fn::GetAtt:
        - EC2Instance
        - PublicIp
  EIPAddress:
    Description: EIP-address of ec2-instance
    Value:
      Ref: EIPAddress
