---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Instance
Parameters:
  Environment:
    Type: String
    Description: Used for miscellaneous object names and tags
    AllowedValues:
      - "dev"
      - "test"
      - "qa"
      - "prod"
    Default: dev

  HostedZoneName:
    Description: The route53 HostedZoneName.
    Type: String

  Ec2Eip:
    Description: EIP of the Instance
    Type: String

Resources:

  DNSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Join ['', [!Ref Environment,'.',!Ref HostedZoneName,]]
      Type: A
      TTL: 900
      ResourceRecords: 
        - !Ref Ec2Eip
 
Outputs:
  HostedZoneName:
    Description: Name Of the HostedZone
    Value: !Ref HostedZoneName
  
