---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creation Of Simple S3 Bucket.

Parameters:
  Environment:
    Type: String
    Description: Used for miscellaneous object names and tags
    AllowedValues:
      - "dev"
      - "test"
      - "qa"
      - "prod"
    Default: dev
  BucketName:
    Type: String
    Description: The name of the S3 Bucket to create
    Default: moove-test-

Resources:
  AssetS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Join:
          - ""
          - - Ref: BucketName
            - Ref: Environment
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              - - moove-test-
                - Ref: Environment
      VersioningConfiguration:
        Status: Enabled

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetS3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowPublicRead
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Principal:
              AWS:
                - "766964217053"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: AssetS3Bucket
                  - "/*"

Outputs:
  AssetS3Bucket:
    Value: !Ref AssetS3Bucket
    Description: S3 Bucket for object storage
